"""restore job columns

Revision ID: 1e6cd4b33314
Revises: 1a4bcae222d5
Create Date: 2026-04-07 15:46:20.854652

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e6cd4b33314"
down_revision: Union[str, Sequence[str], None] = "1a4bcae222d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("title", sa.String(), nullable=True))
    op.add_column("jobs", sa.Column("required_skills", sa.JSON(), nullable=True))
    op.add_column("jobs", sa.Column("min_experience", sa.Integer(), nullable=True))
    op.drop_index(op.f("ix_jobs_id"), table_name="jobs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_jobs_id"), "jobs", ["id"], unique=False)
    op.drop_column("jobs", "min_experience")
    op.drop_column("jobs", "required_skills")
    op.drop_column("jobs", "title")
    # ### end Alembic commands ###
