"""update job table

Revision ID: 9f6cf6b90795
Revises:
Create Date: 2026-04-07 15:39:01.718007

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f6cf6b90795"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "salary")
    op.drop_column("jobs", "skills")
    op.drop_column("jobs", "experience")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column("experience", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "jobs", sa.Column("skills", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "jobs",
        sa.Column(
            "salary",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
